# Run as root so PAM eauth can read /etc/shadow inside the container.
user: root
interface: 0.0.0.0
log_level_logfile: info
timeout: 10
gather_job_timeout: 15
presence_events: True
autosign_file: /etc/salt/autosign.conf
extension_modules: /srv/salt-ext

nodegroups:
  webservers: 'G@roles:web'
  databases: 'G@roles:db'
  production: 'G@environment:production'
worker_threads: 3
