rest_cherrypy:
  host: 0.0.0.0
  port: 8000
  disable_ssl: True

netapi_enable_clients:
  - local
  - local_async
  - local_batch
  - runner
  - runner_async
  - wheel
  - wheel_async

external_auth:
  pam:
    saltadmin:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'
    viewer:
      - 'test.*'
      - 'grains.*'
      - 'sys.*'
      - 'pillar.get'
      - '@jobs'
      - '@runner':
          - 'jobs.*'
          - 'manage.*'
          - 'cache.grains'
          - 'fileserver.*'
  ldap:
    salt-admins%:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'
    salt-operators%:
      - 'test.*'
      - 'state.*'
      - 'grains.*'
      - 'pillar.*'
      - 'sys.*'
      - 'match.*'
      - 'saltutil.refresh_pillar'
      - 'saltutil.running'
      - 'status.*'
      - 'disk.usage'
      - 'network.interfaces'
      - 'pkg.list_pkgs'
      - 'service.get_all'
      - 'schedule.list'
      - '@jobs'
      - '@runner':
          - 'jobs.*'
          - 'manage.*'
          - 'cache.grains'
          - 'fileserver.*'
          - 'doc.*'

token_expire: 43200
